config/routes.rb
MyStore::Application.routes.draw do
  resources :items do
    member do
      post :upvote
    end
  end

  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to  :user
  has_many    :positions
  has_many    :items, through: :positions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, ImageUploader
  belongs_to :imageable, polymorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, :description, presence: true

  has_many  :positions
  has_many  :carts, through: :positions
  has_many  :comments, as: :commentable
  has_one   :image, as: :imageable
  has_and_belongs_to_many :orders


  def image=(new_image)
    if !self.image || new_record?
      @image = Image.create({file: new_image, imageable: self})
    elsif self.image
      self.image.update_attributes({file: new_image})
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :items

  before_save do
    raise 'No items in order' if items.empty?
  end

  def calculate_total
    write_attribute :total, items.map(&:price).inject(:+)
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one   :cart
  has_many  :orders
  has_many  :comments


  before_destroy { self.cart.destroy }

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :check_if_admin
  # layout 'admin'

  def users_count
    @users_count = User.count
    render layout: 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def render_403
    render file: 'public/403.html', status: 403
  end

  def render_404
    render file: 'public/404.html', status: 404
  end

  def check_if_admin
    #render_403 unless params[:admin]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item,       only: [:show, :edit, :update, :destroy, :upvote]
  before_filter :check_if_admin,  only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item
    @items = @items.where('price >= ?', params[:price_from])        if params[:price_from]
    @items = @items.where('created_at >= ?', 1.day.ago)             if params[:today]
    @items = @items.where('votes_count >= ?', params[:votes_from])  if params[:votes_from]
    @items = @items.order('votes_count DESC', 'price')
    @items = @items.includes :image
  end

  def expensive
    @items = Item.where('price > 1000')
    render :index
  end

  # /items/1 GET
  def show
  end

  # /items/new GET
  def new
    @item = Item.new
  end

  # /items/1/edit GET
  def edit
  end

  # /items POST
  def create
    @item = Item.create item_params
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  # /items/1 PUT
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      flash[:success] = 'Item has been successfully updated.'
      redirect_to item_path(@item)
    else
      flash.now[:error] = 'You made mistakes in your form! Please correct them.'
      render :edit
    end
  end

  # /items/1 DELETE
  def destroy
    @item.destroy
    # redirect_to action: :index
    render json: { success: true }
    ItemsMailer.item_destroyed(@item).deliver
  end

  def upvote
    @item.increment! :votes_count
    redirect_to action: :index
  end

  private

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def item_params
    params.require(:item).permit(:price, :name, :real, :weight, :description, :image)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_images(s)
    s.gsub! /\s(http:\/\/.*?\.(png|jpg))\s/, ' <p><img src="\1" /></p> '
    s.html_safe
  end

  def urls_to_links(s)
    s.gsub! /\s(https?:\/\/.*?)\s/, ' <a href="\1" />\1</a> '
    s.html_safe
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %>

app/views/items/_form.html.haml
= f.input :price
= f.input :name
= f.input :description
= f.input :weight
= f.file_field :image

app/views/items/edit.html.haml
%h1 Edit item

= simple_form_for @item do |f|
  = render partial: 'form', locals: { f: f }
  %p= f.submit 'Update item'

app/views/items/index.html.erb
<h1>Items</h1>
<%= render partial: 'shared/email' %>

<% if @items.empty? %>
    <b>No items in store</b>
<% else %>
    <table class="items">
      <tr>
        <th>ID</th>
        <th>Image</th>
        <th>Name</th>
        <th>Price</th>
        <th>Rating</th>
        <th>Created At</th>
        <th>Actions</th>
      </tr>
      <% @items.each do |item| %>
        <tr data-item-id="<%= item.id %>">
          <td><%= item.id %></td>
          <td><%= image_tag item.image.file, width: '50px' if item.image %></td>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td><%= item.votes_count %></td>
          <td><%= item.created_at %></td>
          <td>
            <%= link_to 'Vote', upvote_item_path(item) %>
            <%= link_to 'Edit', edit_item_path(item) %>
            <span class="deleteAction">Remove</span>
          </td>
        </tr>
      <% end %>
    </table>
<% end %>

app/views/items/new.html.haml
%h1 Create new item

= simple_form_for @item do |f|

  = render partial: 'form', locals: { f: f }
  %p= f.submit 'Create item'

app/views/items/show.html.haml
%h1= @item.name
%ul
  %li= @item.price
  %li= urls_to_links urls_to_images(@item.description)
  %li #{t('item.weight')}: #{@item.weight} kg.
  = image_tag(@item.image.file) if @item.image

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="adminPanel">
    ADMIN
  </div>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: red;"><%= flash[:error] %></p>
<p style="color: green;"><%= flash[:success] %></p>
<%= yield %>

</body>
</html>

app/views/shared/_email.html.erb
<div class="email">
  some@some.some
</div>